.code
	; read n into r1 (input port is 0, so rs must be 0)
	in r1, r0

	; i = 1
	mov r2, 1
	mov r3, 0
	mov r4, 1

	; set output port register to 1 (sim prints only if regs[rd] == 1)
	mov r30, 1

	; load absolute jump targets
	ld r5, :end ; r3
	ld r6, :print ; r4
	ld r7, :loop ; r5

:loop
	; if i > n → end
	brgt r3, r2, r1
	; r8 = r3 + r4
	add r8, r3, r4
	mov r3, r4
	mov r4, r8
	; else print
	br r4

:print
	out r30, r4
	addi r2, 1
	br r7

:end
	halt
